//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CountAndSortWinFormsAppNetFr4.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CountAndSortWinFormsAppNetFr4.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Data.
        /// </summary>
        internal static string ButtonProcessData {
            get {
                return ResourceManager.GetString("ButtonProcessData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Points History.
        /// </summary>
        internal static string ButtonSaveHistory {
            get {
                return ResourceManager.GetString("ButtonSaveHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File.
        /// </summary>
        internal static string ButtonSelectFile {
            get {
                return ResourceManager.GetString("ButtonSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Output Folder Location.
        /// </summary>
        internal static string ButtonSelectOutputFolder {
            get {
                return ResourceManager.GetString("ButtonSelectOutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Duplicate Rows.
        /// </summary>
        internal static string CheckBoxRemoveDuplicatesRows {
            get {
                return ResourceManager.GetString("CheckBoxRemoveDuplicatesRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renumber Order.
        /// </summary>
        internal static string CheckBoxRenumberTheOrder {
            get {
                return ResourceManager.GetString("CheckBoxRenumberTheOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All Rows.
        /// </summary>
        internal static string CheckBoxSelectAll {
            get {
                return ResourceManager.GetString("CheckBoxSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by Name.
        /// </summary>
        internal static string CheckBoxSortByName {
            get {
                return ResourceManager.GetString("CheckBoxSortByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Points:.
        /// </summary>
        internal static string LabelAverage {
            get {
                return ResourceManager.GetString("LabelAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Column Separator Symbol:.
        /// </summary>
        internal static string LabelDataStructureSeparatorIs {
            get {
                return ResourceManager.GetString("LabelDataStructureSeparatorIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Count:.
        /// </summary>
        internal static string LabelFileCount {
            get {
                return ResourceManager.GetString("LabelFileCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Sum:.
        /// </summary>
        internal static string LabelTotalSum {
            get {
                return ResourceManager.GetString("LabelTotalSum", resourceCulture);
            }
        }
    }
}
