//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CountAndSortWinFormsAppNetFr4.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CountAndSortWinFormsAppNetFr4.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to files.
        /// </summary>
        internal static string AFiles {
            get {
                return ResourceManager.GetString("AFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analysis.
        /// </summary>
        internal static string Analysis {
            get {
                return ResourceManager.GetString("Analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to - ... and other .
        /// </summary>
        internal static string AndOther {
            get {
                return ResourceManager.GetString("AndOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save detailed results to a file?.
        /// </summary>
        internal static string AskToSaveResults {
            get {
                return ResourceManager.GetString("AskToSaveResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BATCH FILE PROCESSING RESULTS.
        /// </summary>
        internal static string BatchProcessingResultsTitle {
            get {
                return ResourceManager.GetString("BatchProcessingResultsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export data.
        /// </summary>
        internal static string ButtonExport {
            get {
                return ResourceManager.GetString("ButtonExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Data.
        /// </summary>
        internal static string ButtonProcessData {
            get {
                return ResourceManager.GetString("ButtonProcessData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Points History.
        /// </summary>
        internal static string ButtonSaveHistory {
            get {
                return ResourceManager.GetString("ButtonSaveHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File.
        /// </summary>
        internal static string ButtonSelectFile {
            get {
                return ResourceManager.GetString("ButtonSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Output Folder Location.
        /// </summary>
        internal static string ButtonSelectOutputFolder {
            get {
                return ResourceManager.GetString("ButtonSelectOutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table settings.
        /// </summary>
        internal static string ButtonTableSettings {
            get {
                return ResourceManager.GetString("ButtonTableSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Duplicate Rows.
        /// </summary>
        internal static string CheckBoxRemoveDuplicatesRows {
            get {
                return ResourceManager.GetString("CheckBoxRemoveDuplicatesRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renumber Order.
        /// </summary>
        internal static string CheckBoxRenumberTheOrder {
            get {
                return ResourceManager.GetString("CheckBoxRenumberTheOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All Rows.
        /// </summary>
        internal static string CheckBoxSelectAll {
            get {
                return ResourceManager.GetString("CheckBoxSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by Name.
        /// </summary>
        internal static string CheckBoxSortByName {
            get {
                return ResourceManager.GetString("CheckBoxSortByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check mark all.
        /// </summary>
        internal static string CheckMarkAll {
            get {
                return ResourceManager.GetString("CheckMarkAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you set which column of the displayed table the points should be counted in..
        /// </summary>
        internal static string ColumnToCountToolTip {
            get {
                return ResourceManager.GetString("ColumnToCountToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separators for displaying data in a table..
        /// </summary>
        internal static string DataStructureSeparatorToolTip {
            get {
                return ResourceManager.GetString("DataStructureSeparatorToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date and time:.
        /// </summary>
        internal static string DateTimeLabel {
            get {
                return ResourceManager.GetString("DateTimeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DETAILED RESULTS FOR EACH FILE.
        /// </summary>
        internal static string DetailedResultsHeader {
            get {
                return ResourceManager.GetString("DetailedResultsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnoses.
        /// </summary>
        internal static string Diagnoses {
            get {
                return ResourceManager.GetString("Diagnoses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse Folder.
        /// </summary>
        internal static string DialogBrowseFolder {
            get {
                return ResourceManager.GetString("DialogBrowseFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Folder.
        /// </summary>
        internal static string DialogCreateNewFolder {
            get {
                return ResourceManager.GetString("DialogCreateNewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Text files (*.txt)|*.txt|All files (*.*)|*.*&quot;.
        /// </summary>
        internal static string DialogFilterTextFiles {
            get {
                return ResourceManager.GetString("DialogFilterTextFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folder for saving processed file.
        /// </summary>
        internal static string DialogSelectOutputFolder {
            get {
                return ResourceManager.GetString("DialogSelectOutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doctors.
        /// </summary>
        internal static string Doctors {
            get {
                return ResourceManager.GetString("Doctors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving file.
        /// </summary>
        internal static string ErrorSavingFile {
            get {
                return ResourceManager.GetString("ErrorSavingFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving results: {0}.
        /// </summary>
        internal static string ErrorSavingResults {
            get {
                return ResourceManager.GetString("ErrorSavingResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extended Statistics.
        /// </summary>
        internal static string ExtendedStatistics {
            get {
                return ResourceManager.GetString("ExtendedStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facilities.
        /// </summary>
        internal static string Facilities {
            get {
                return ResourceManager.GetString("Facilities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UNPROCESSED FILES.
        /// </summary>
        internal static string FailedFilesHeader {
            get {
                return ResourceManager.GetString("FailedFilesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason:.
        /// </summary>
        internal static string FailureReasonLabel {
            get {
                return ResourceManager.GetString("FailureReasonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file.
        /// </summary>
        internal static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to file access problem.
        /// </summary>
        internal static string FileAccessProblem {
            get {
                return ResourceManager.GetString("FileAccessProblem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File list:.
        /// </summary>
        internal static string FileList {
            get {
                return ResourceManager.GetString("FileList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found:.
        /// </summary>
        internal static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File processing.
        /// </summary>
        internal static string FileProcessing {
            get {
                return ResourceManager.GetString("FileProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecting files for processing:.
        /// </summary>
        internal static string FileSelection {
            get {
                return ResourceManager.GetString("FileSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Points:.
        /// </summary>
        internal static string HistoryAveragePoints {
            get {
                return ResourceManager.GetString("HistoryAveragePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created:.
        /// </summary>
        internal static string HistoryCreated {
            get {
                return ResourceManager.GetString("HistoryCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Duplicates Removed:.
        /// </summary>
        internal static string HistoryDuplicates {
            get {
                return ResourceManager.GetString("HistoryDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Count:.
        /// </summary>
        internal static string HistoryFileCount {
            get {
                return ResourceManager.GetString("HistoryFileCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to points_history.
        /// </summary>
        internal static string HistoryFileName {
            get {
                return ResourceManager.GetString("HistoryFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processed Points History.
        /// </summary>
        internal static string HistoryHeader {
            get {
                return ResourceManager.GetString("HistoryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Points:.
        /// </summary>
        internal static string HistoryTotalPoints {
            get {
                return ResourceManager.GetString("HistoryTotalPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identifier.
        /// </summary>
        internal static string Identifier {
            get {
                return ResourceManager.GetString("Identifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column &quot;Date of Procedure&quot;.
        /// </summary>
        internal static string LabelDateOfServiceColumn {
            get {
                return ResourceManager.GetString("LabelDateOfServiceColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column &quot;Diagnosis&quot;.
        /// </summary>
        internal static string LabelDiagnosisColumn {
            get {
                return ResourceManager.GetString("LabelDiagnosisColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File export separator.
        /// </summary>
        internal static string LabelExportDataSeparator {
            get {
                return ResourceManager.GetString("LabelExportDataSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Count:.
        /// </summary>
        internal static string LabelFileCount {
            get {
                return ResourceManager.GetString("LabelFileCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column &quot;Birth Identifier&quot;.
        /// </summary>
        internal static string LabelIdColumn {
            get {
                return ResourceManager.GetString("LabelIdColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Separator for imported Data.
        /// </summary>
        internal static string LabelImportDataSeparator {
            get {
                return ResourceManager.GetString("LabelImportDataSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column &quot;Name&quot;.
        /// </summary>
        internal static string LabelNameColumn {
            get {
                return ResourceManager.GetString("LabelNameColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column &quot;Points&quot;.
        /// </summary>
        internal static string LabelPointsColumn {
            get {
                return ResourceManager.GetString("LabelPointsColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column &quot;Medical procedure&quot;.
        /// </summary>
        internal static string LabelServiceCodeColumn {
            get {
                return ResourceManager.GetString("LabelServiceCodeColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Sum:.
        /// </summary>
        internal static string LabelTotalSum {
            get {
                return ResourceManager.GetString("LabelTotalSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lines.
        /// </summary>
        internal static string Lines {
            get {
                return ResourceManager.GetString("Lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string ListViewColumnDate {
            get {
                return ResourceManager.GetString("ListViewColumnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string ListViewColumnFile {
            get {
                return ResourceManager.GetString("ListViewColumnFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        internal static string ListViewColumnPath {
            get {
                return ResourceManager.GetString("ListViewColumnPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        internal static string ListViewColumnPoints {
            get {
                return ResourceManager.GetString("ListViewColumnPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string ListViewColumnSize {
            get {
                return ResourceManager.GetString("ListViewColumnSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of points:.
        /// </summary>
        internal static string MaximumPoints {
            get {
                return ResourceManager.GetString("MaximumPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string MessageDone {
            get {
                return ResourceManager.GetString("MessageDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to process these files again?.
        /// </summary>
        internal static string MessageDoYouWantProcessAgain {
            get {
                return ResourceManager.GetString("MessageDoYouWantProcessAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to save the detailed result to a file?.
        /// </summary>
        internal static string MessageDoYouWantSaveDetailedResult {
            get {
                return ResourceManager.GetString("MessageDoYouWantSaveDetailedResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MessageError {
            get {
                return ResourceManager.GetString("MessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving history.
        /// </summary>
        internal static string MessageErrorSavingHistory {
            get {
                return ResourceManager.GetString("MessageErrorSavingHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export client data.
        /// </summary>
        internal static string MessageExportDataDialogTitle {
            get {
                return ResourceManager.GetString("MessageExportDataDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error exporting data {0}!.
        /// </summary>
        internal static string MessageExportError {
            get {
                return ResourceManager.GetString("MessageExportError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data exported successfully!.
        /// </summary>
        internal static string MessageExportSuccess {
            get {
                return ResourceManager.GetString("MessageExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file has already been processed. Do you want to process it again?.
        /// </summary>
        internal static string MessageFileAlreadyProcessed {
            get {
                return ResourceManager.GetString("MessageFileAlreadyProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading file:.
        /// </summary>
        internal static string MessageFileError {
            get {
                return ResourceManager.GetString("MessageFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected file does not exist..
        /// </summary>
        internal static string MessageFileNotExist {
            get {
                return ResourceManager.GetString("MessageFileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to the selected files have already been processed:.
        /// </summary>
        internal static string MessageFilesAlreadyBeenProcessed {
            get {
                return ResourceManager.GetString("MessageFilesAlreadyBeenProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History saved successfully to file.
        /// </summary>
        internal static string MessageHistorySaved {
            get {
                return ResourceManager.GetString("MessageHistorySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string MessageInfo {
            get {
                return ResourceManager.GetString("MessageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information about file selection.
        /// </summary>
        internal static string MessageInfoFileSelection {
            get {
                return ResourceManager.GetString("MessageInfoFileSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected column for points does not exist in the file. Please select a valid column..
        /// </summary>
        internal static string MessageInvalidColumn {
            get {
                return ResourceManager.GetString("MessageInvalidColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error changing language: {0}.
        /// </summary>
        internal static string MessageLanguageChangeError {
            get {
                return ResourceManager.GetString("MessageLanguageChangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You do not have write access to the folder.
        /// </summary>
        internal static string MessageNoAccessToFolder {
            get {
                return ResourceManager.GetString("MessageNoAccessToFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No files selected.
        /// </summary>
        internal static string MessageNoFilesSelected {
            get {
                return ResourceManager.GetString("MessageNoFilesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No history available to save..
        /// </summary>
        internal static string MessageNoHistoryToSave {
            get {
                return ResourceManager.GetString("MessageNoHistoryToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No rows are marked for processing. Please mark the rows you want to process..
        /// </summary>
        internal static string MessageNoRowsSelected {
            get {
                return ResourceManager.GetString("MessageNoRowsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error processing data:.
        /// </summary>
        internal static string MessageProcessingError {
            get {
                return ResourceManager.GetString("MessageProcessingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data has been processed and saved to file:
        ///	{0}
        ///			
        ///Number of deleted rows: {1}
        ///Original number of rows: {2}
        ///Number of processed rows: {3}
        ///			
        ///Original points: {4}
        ///Points after processing: {5}.
        /// </summary>
        internal static string MessageProcessingResults {
            get {
                return ResourceManager.GetString("MessageProcessingResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a file first..
        /// </summary>
        internal static string MessageSelectFile {
            get {
                return ResourceManager.GetString("MessageSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The table shows a preview of the first file. All files will be processed after clicking &apos;Process Data&apos;..
        /// </summary>
        internal static string MessageShowsPreviewAllFilesProcessed {
            get {
                return ResourceManager.GetString("MessageShowsPreviewAllFilesProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating statistics..
        /// </summary>
        internal static string MessageStatisticsError {
            get {
                return ResourceManager.GetString("MessageStatisticsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported file format. Please select .xlsx or .csv..
        /// </summary>
        internal static string MessageUnsupportedFormat {
            get {
                return ResourceManager.GetString("MessageUnsupportedFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string MessageWarning {
            get {
                return ResourceManager.GetString("MessageWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum number of points:.
        /// </summary>
        internal static string MinimumPoints {
            get {
                return ResourceManager.GetString("MinimumPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data is available for statistics..
        /// </summary>
        internal static string NoDataAvailableForStatistics {
            get {
                return ResourceManager.GetString("NoDataAvailableForStatistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Output file:.
        /// </summary>
        internal static string OutputFileLabel {
            get {
                return ResourceManager.GetString("OutputFileLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points after:.
        /// </summary>
        internal static string PointsAfterLabel {
            get {
                return ResourceManager.GetString("PointsAfterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points before:.
        /// </summary>
        internal static string PointsBeforeLabel {
            get {
                return ResourceManager.GetString("PointsBeforeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points difference: {0}.
        /// </summary>
        internal static string PointsDifference {
            get {
                return ResourceManager.GetString("PointsDifference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points difference:.
        /// </summary>
        internal static string PointsDifferenceLabel {
            get {
                return ResourceManager.GetString("PointsDifferenceLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to points, removed.
        /// </summary>
        internal static string PointsRemoved {
            get {
                return ResourceManager.GetString("PointsRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processed: {0} of {1} files.
        /// </summary>
        internal static string ProcessedFilesCount {
            get {
                return ResourceManager.GetString("ProcessedFilesCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File processing completed..
        /// </summary>
        internal static string ProcessingComplete {
            get {
                return ResourceManager.GetString("ProcessingComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process selected.
        /// </summary>
        internal static string ProcessSelected {
            get {
                return ResourceManager.GetString("ProcessSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removed duplicates:.
        /// </summary>
        internal static string RemovedDuplicatesLabel {
            get {
                return ResourceManager.GetString("RemovedDuplicatesLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Results were successfully saved to file:\n{0}.
        /// </summary>
        internal static string ResultsSavedSuccessfully {
            get {
                return ResourceManager.GetString("ResultsSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows after:.
        /// </summary>
        internal static string RowsAfterLabel {
            get {
                return ResourceManager.GetString("RowsAfterLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows before:.
        /// </summary>
        internal static string RowsBeforeLabel {
            get {
                return ResourceManager.GetString("RowsBeforeLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selected.
        /// </summary>
        internal static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUCCESSFULLY PROCESSED FILES.
        /// </summary>
        internal static string SuccessfulFilesHeader {
            get {
                return ResourceManager.GetString("SuccessfulFilesHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of files selected:.
        /// </summary>
        internal static string TotalFilesSelected {
            get {
                return ResourceManager.GetString("TotalFilesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Points.
        /// </summary>
        internal static string TotalPoints {
            get {
                return ResourceManager.GetString("TotalPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total points after: {0}.
        /// </summary>
        internal static string TotalPointsAfter {
            get {
                return ResourceManager.GetString("TotalPointsAfter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total points before: {0}.
        /// </summary>
        internal static string TotalPointsBefore {
            get {
                return ResourceManager.GetString("TotalPointsBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncheck mark all.
        /// </summary>
        internal static string UncheckMarkAll {
            get {
                return ResourceManager.GetString("UncheckMarkAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Finances.
        /// </summary>
        internal static string ViewByFinances {
            get {
                return ResourceManager.GetString("ViewByFinances", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Months.
        /// </summary>
        internal static string ViewByMonths {
            get {
                return ResourceManager.GetString("ViewByMonths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Points.
        /// </summary>
        internal static string ViewByPoints {
            get {
                return ResourceManager.GetString("ViewByPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to By Services.
        /// </summary>
        internal static string ViewByServices {
            get {
                return ResourceManager.GetString("ViewByServices", resourceCulture);
            }
        }
    }
}
