//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CountAndSortWinFormsAppNetFr4.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CountAndSortWinFormsAppNetFr4.Properties.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Data.
        /// </summary>
        internal static string ButtonProcessData {
            get {
                return ResourceManager.GetString("ButtonProcessData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Points History.
        /// </summary>
        internal static string ButtonSaveHistory {
            get {
                return ResourceManager.GetString("ButtonSaveHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select File.
        /// </summary>
        internal static string ButtonSelectFile {
            get {
                return ResourceManager.GetString("ButtonSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Output Folder Location.
        /// </summary>
        internal static string ButtonSelectOutputFolder {
            get {
                return ResourceManager.GetString("ButtonSelectOutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove Duplicate Rows.
        /// </summary>
        internal static string CheckBoxRemoveDuplicatesRows {
            get {
                return ResourceManager.GetString("CheckBoxRemoveDuplicatesRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renumber Order.
        /// </summary>
        internal static string CheckBoxRenumberTheOrder {
            get {
                return ResourceManager.GetString("CheckBoxRenumberTheOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All Rows.
        /// </summary>
        internal static string CheckBoxSelectAll {
            get {
                return ResourceManager.GetString("CheckBoxSelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort by Name.
        /// </summary>
        internal static string CheckBoxSortByName {
            get {
                return ResourceManager.GetString("CheckBoxSortByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Here you set which column needs to be calculated..
        /// </summary>
        internal static string ColumnToCountToolTip {
            get {
                return ResourceManager.GetString("ColumnToCountToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse Folder.
        /// </summary>
        internal static string DialogBrowseFolder {
            get {
                return ResourceManager.GetString("DialogBrowseFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Folder.
        /// </summary>
        internal static string DialogCreateNewFolder {
            get {
                return ResourceManager.GetString("DialogCreateNewFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Text files (*.txt)|*.txt|All files (*.*)|*.*&quot;.
        /// </summary>
        internal static string DialogFilterTextFiles {
            get {
                return ResourceManager.GetString("DialogFilterTextFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select folder for saving processed file.
        /// </summary>
        internal static string DialogSelectOutputFolder {
            get {
                return ResourceManager.GetString("DialogSelectOutputFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Points:.
        /// </summary>
        internal static string HistoryAveragePoints {
            get {
                return ResourceManager.GetString("HistoryAveragePoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created:.
        /// </summary>
        internal static string HistoryCreated {
            get {
                return ResourceManager.GetString("HistoryCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Duplicates Removed:.
        /// </summary>
        internal static string HistoryDuplicates {
            get {
                return ResourceManager.GetString("HistoryDuplicates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Count:.
        /// </summary>
        internal static string HistoryFileCount {
            get {
                return ResourceManager.GetString("HistoryFileCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to points_history.
        /// </summary>
        internal static string HistoryFileName {
            get {
                return ResourceManager.GetString("HistoryFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processed Points History.
        /// </summary>
        internal static string HistoryHeader {
            get {
                return ResourceManager.GetString("HistoryHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Points:.
        /// </summary>
        internal static string HistoryTotalPoints {
            get {
                return ResourceManager.GetString("HistoryTotalPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table Column Separator Symbol:.
        /// </summary>
        internal static string LabelDataStructureSeparatorIs {
            get {
                return ResourceManager.GetString("LabelDataStructureSeparatorIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Count:.
        /// </summary>
        internal static string LabelFileCount {
            get {
                return ResourceManager.GetString("LabelFileCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points column (number):.
        /// </summary>
        internal static string LabelPointsColumn {
            get {
                return ResourceManager.GetString("LabelPointsColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Sum:.
        /// </summary>
        internal static string LabelTotalSum {
            get {
                return ResourceManager.GetString("LabelTotalSum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string ListViewColumnDate {
            get {
                return ResourceManager.GetString("ListViewColumnDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        internal static string ListViewColumnFile {
            get {
                return ResourceManager.GetString("ListViewColumnFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Points.
        /// </summary>
        internal static string ListViewColumnPoints {
            get {
                return ResourceManager.GetString("ListViewColumnPoints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        internal static string MessageDone {
            get {
                return ResourceManager.GetString("MessageDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string MessageError {
            get {
                return ResourceManager.GetString("MessageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error saving history.
        /// </summary>
        internal static string MessageErrorSavingHistory {
            get {
                return ResourceManager.GetString("MessageErrorSavingHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This file has already been processed. Do you want to process it again?.
        /// </summary>
        internal static string MessageFileAlreadyProcessed {
            get {
                return ResourceManager.GetString("MessageFileAlreadyProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error reading file:.
        /// </summary>
        internal static string MessageFileError {
            get {
                return ResourceManager.GetString("MessageFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected file does not exist..
        /// </summary>
        internal static string MessageFileNotExist {
            get {
                return ResourceManager.GetString("MessageFileNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History saved successfully to file:.
        /// </summary>
        internal static string MessageHistorySaved {
            get {
                return ResourceManager.GetString("MessageHistorySaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string MessageInfo {
            get {
                return ResourceManager.GetString("MessageInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected column for points does not exist in the file. Please select a valid column..
        /// </summary>
        internal static string MessageInvalidColumn {
            get {
                return ResourceManager.GetString("MessageInvalidColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error changing language: {0}.
        /// </summary>
        internal static string MessageLanguageChangeError {
            get {
                return ResourceManager.GetString("MessageLanguageChangeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No history available to save..
        /// </summary>
        internal static string MessageNoHistoryToSave {
            get {
                return ResourceManager.GetString("MessageNoHistoryToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No rows are marked for processing. Please mark the rows you want to process..
        /// </summary>
        internal static string MessageNoRowsSelected {
            get {
                return ResourceManager.GetString("MessageNoRowsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error processing data:.
        /// </summary>
        internal static string MessageProcessingError {
            get {
                return ResourceManager.GetString("MessageProcessingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data has been processed and saved to file:
        ///	{0}
        ///			
        ///Number of deleted rows: {1}
        ///Original number of rows: {2}
        ///Number of processed rows: {3}
        ///			
        ///Original points: {4}
        ///Points after processing: {5}.
        /// </summary>
        internal static string MessageProcessingResults {
            get {
                return ResourceManager.GetString("MessageProcessingResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a file first..
        /// </summary>
        internal static string MessageSelectFile {
            get {
                return ResourceManager.GetString("MessageSelectFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error updating statistics..
        /// </summary>
        internal static string MessageStatisticsError {
            get {
                return ResourceManager.GetString("MessageStatisticsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        internal static string MessageWarning {
            get {
                return ResourceManager.GetString("MessageWarning", resourceCulture);
            }
        }
    }
}
